---
title: "My title."
author: "Joe Smith"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    toc: true
    keep_md: true
    includes:
      in_header: header.html
bibliography: ref.bib    
---

```{r options, echo = F}
opts_chunk$set(fig.path = "figures/", comment = NA, results = 'markup', tidy = F, message = F, warning = F, echo = F)
```

```{r par}
alpha <- 0.05
```

```{r inc, cache = FALSE}
library(plyr)
library(ggplot2)
library(gridExtra)

library(magrittr)

library(pander)

library(data.table)
```

```{r settings, cache = FALSE}
theme_set(theme_light())

panderOptions('table.style', 'rmarkdown')

panderOptions('table.split.table', Inf)
panderOptions('knitr.auto.asis', FALSE)

panderOptions('table.alignment.default', 'left')
```

# Figures

## Side-by-side figures

```{r fig_side_by_side, , fig.show = "hold", out.width = "50%"}
plot(1:10)
plot(rnorm(10))
```

# Tables

```{r tab, echo = FALSE, message = FALSE, warnings = FALSE, results = 'asis'}
pander(head(iris), style = 'rmarkdown', digits = 2, big.mark = ",")
```

# Custom header

Specify the custom header:

```
output:
  html_document:
    includes:
      in_header: header.html
```

## Disable Google robots

Add the following line to disable that your web page is indexed by Google, etc.

```
<meta name="robots" content="noindex">
```

